insert into Player(firstName,lastName,university,position,age)
values
('Travis','Hunter','Colorado','CB',22),
('Abdul','Carter','Penn State','EDGE',22), 
('Cameron','Ward','Miami (FL)','QB',22), 
('Mason','Graham','Michigan','DL3T',22), 
('Ashton','Jeanty','Boise State','RB',22),
('Shedeur','Sanders','Colorado','QB',22),
('Tyler','Warren','Penn State','TE',22),
('Armand','Membou','Missouri','OT',22), 
('Tetairoa','McMillan','Arizon','WR',22), 
('Will','Campbell','LSU','OT',22), 
('Nick','Emmanwori','South Carolina','S',22), 
('Shemar','Stewart','Texas A&M','EDGE',22), 
('Mykel','Williams','Georgia','EDGE',22), 
('Matthew','Golden','Texas','WR',22), 
('Kelvin','Banks Jr.','Texas','OT',22), 
('Malaki','Starks','Georgia','S',22), 
('Walter','Nolen','Ole Miss','DL3T',22), 
('Will','Johnson','Michigan','CB',22),
('Derrick','Harmon','Oregon','DL3T',22), 
('Luther','Burden III','Missouri','WR',22), 
('Jalon','Walker','Georgia','OLB',22), 
('Mike','Green','Marshall','EDGE',22), 
('Donovan','Ezeiruaku','Boston College','EDGE',22), 
('Jahdae','Barron','Texas','CB',22), 
('Emeka','Egbuka','Ohio State','WR',22), 
('Josh','Simmons','Ohio State','OT',22), 
('Jihaad','Campbell','Alabama','ILB',22), 
('James','Pearce Jr.','Tennessee','EDGE',22),
('Grey','Zabel','North Dakota State','OG',22),
('Colston','Loveland','Michigan','TE',22),  
('Knneth','Grant','Michigan','DL1T',22), 
('Jaxson','Dart','Ole Miss','QB',22),
('Josh','Conerly Jr.','Oregon','OT',22),
('Tyler','Booker','Alabama','OG',22), 
('Shavon','Revel Jr.','East Carolina','CB',22), 
('Trey','Amos','Ole Miss','CB',22), 
('Aireonta','Ersery','Minnesota','OT',22), 
('Maxwell','Hairston','Kentucky','CB',22), 
('Darien','Porter','Iowa State','CB',22), 
('Omarion','Hampton','North Carolina','RB',22),
('Nic','Scourton','Texas A&M','EDGE',22),
('Tyleik','Williams','Ohio State','DL1T',22),
('Benjamin','Morrison','Notre Dame','CB',22),
('Princely','Umanmielen','Ole Miss','EDGE',22),
('Alfred','Collins','Texas','DL3T',22),
('Carson','Schwesinger','UCLA','ILB',22),
('Jayden','Higgins','Iowa State','WR',22),
('Jonah','Savaiinaea','Arizona','OG',22), 
('Landon','Jackson','Arkansas','EDGE',22), 
('Darius','Alexander','Toledo','DL3T',22), 
('Cameron','Skattebo','Arizona State','RB',22), 
('Wyatt','Milum','West Virginia','T',22), 
('Jordan','Burch','Oregon','EDGE',22), 
('J.T.','Tuimoloau','Ohio State','EDGE',22),
('Donovan','Jackson','Ohio State','OG',22),
('Tre','Harris','Ole Miss','WR',22),
('Jalen','Milroe','Alabama','QB',22),
('Cameron','Williams','Texas','OT',22),
('Josaiah','Stewart','Michigan','EDGE',22),
('Azareyeh','Thomas','Florida tate','CB',22),
('T.J.','Sanders','Soth Carolina','D5T',22),
('Elic','yomanor','Stanford','WR',22),
('Omarr','Norman-Lott','Tennessee','DL3T',22),
('Tez','Johnson','Oregon','WRS',22),
('Jack','Sawyer','Ohio State','EDGE',22),
('Bradyn','Swinson','LSU','EDGE',22),
('Deone','Walker','Kentucky','DL1T',22),
('Xavier','Watts','Notre Dame','S',22),
('Kaleb','Johnson','Iowa','RB',22),
('TreVeyon','Henderson','Ohio State','RB',22),
('Kye','Kennard','South Carolina','EDGE',22),
('Quinshon','Judkins','Ohi State','RB',22),
('Jack','Bech','TCU','WR',22),
('Isaiah','Bond','Texas','WR',22),
('Joshua','Farmer','FSU','DL3T',22),
('Marcus','Mbow','Purdue','OG',22),
('Jaylin','Noel','Iowa State','WRS',22),
('Demetrius','Knight Jr.','South Caroina','ILB',22),
('Oluwafemi','Oladejo','UCLA','EDGE',22),
('Tate','Ratledge','Georgia','OG',22),
('Dylan','Sampson','Tennessee','RB',22),
('Mason','Taylor','LSU','TE',22),
('Andrew','Mukuba','Texas','S',22),
('Jared','Wilson','Georgia','OC',22),
('Jordan','Phillips','Maryland','DL1T',22),
('Jalen','Royals','Utah State','WR',22),
('Jacob','Parrish','Kansas State','CN',22),
('Tyler','Shough','Louisville','QB',22),
('Gunnar','Helm','Texas','TE',22),
('Terrance','Ferguson','Oregon','TE',22),
('Zah','Frazier','UTSA','CB',22),
('D.J.','Giddens','Kansas State','RB',22),
('Chris','Paul Jr.','Ole Miss','OLB',22),
('Elijah','Arroyo','Miami (FL)','TE',22),
('Smael','Mondon Jr.','Georgia','OLB',22),
('Savion','Wiliams','TCU','WR',22),
('Harold','Fannin Jr.','Bowling Green','TE',22),
('Ty','Robinson','Nebraska','DL3T',22),
('Xavier','Restrepo','Miami (FL)','WRS',22),
('C.J.','West','Indiana','DL1T',21);